name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      JAVA_OPTS: "-Xmx4g -Dfile.encoding=UTF-8"
      GRADLE_OPTS: "-Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=hdecarne-github"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper  
      - name: Build with Gradle
        run: ./gradlew -s --no-daemon clean build sonarqube
